### ISSUE TITLE
Client not compatible with Unleash 5.x

### ISSUE THREAD

**Issue by HontoNoRoger** [philips-labs/go-unleash-api#23]
When working with the [Terraform provider](https://github.com/philips-labs/terraform-provider-unleash) I noticed the following issue when retrieving project data:

```
json: cannot unmarshal object into Go struct field ProjectDetails.environments of type string
```

This can be reproduced with this API client on an open-source Unleash deployment with version 5.1.8.
The reason is probably, that the project's JSON representation now looks like this for the environments field and thus cannot be parsed correctly:

```json
{
...
"environments": [
    {
      "environment": "development"
    },
    {
      "environment": "production"
    }
  ],
...
}
```

It's not a simple set with strings for the environment name, but of a bit more complex type.

**Comment by jdelucaa** [comment]
Hey 👋 
I've just released a fix in v0.3.8. 🚀 
Thanks for pointing this out.
